window.PORTFOLIO_PROJECTS = [
  {
    id: 0,
    name: "Jas&Mey Ice Cream",
    description: "Premium ice cream brand website with 50+ flavors showcase, online ordering system, and home delivery integration for Baba Dairy.",
    image: "images/projects/jm-logo.png",
    tags: ["javascript", "react", "videoEditing", "css"],
    liveview: "https://babadairy.com",
    alt: "Jas&Mey Ice Cream - Baba Dairy Website",
  },
  {
    id: 1,
    name: "Pooja Furniture",
    description: "Full-featured e-commerce store with product catalog, categories, and seamless shopping experience for a furniture and decor brand.",
    image: "images/projects/pf-logo.png",
    tags: ["javascript", "html", "css", "videoEditing"],
    liveview: "https://poojafurniture.com",
    alt: "Pooja Furniture E-Commerce Website",
  },
  {
    id: 2,
    name: "Garg Jewellers",
    description:
      "Luxury jewellery brand website for The House of Garg — royal exclusivity, premium collections, and a polished e-commerce experience at gargjewellers.co.in.",
    image: "images/projects/garg-logo.svg",
    tags: ["react", "javascript", "css", "videoEditing"],
    liveview: "https://gargjewellers.co.in/",
    alt: "Garg Jewellers — The House of Garg | Royal Exclusivity",
  },
  {
    id: 3,
    name: "Domestic Dial",
    description:
      "Smart home design studio website — 3D visualization, coordinated execution across glazing, joinery, and finishes, plus move-in support under one roof at domesticdial.in.",
    image: "images/projects/domesticdial-logo.png",
    tags: ["react", "javascript", "css", "videoEditing"],
    liveview: "https://domesticdial.in/",
    alt: "Domestic Dial | Smart Design for Modern Living",
  },
  {
    id: 4,
    name: "KGF Farming",
    description:
      "Agriculture and eco-farming platform for Kamauput Growth Farming — vermicompost, organic inputs, and sustainable crop care products with pan-India delivery at kgffarmingindia.com.",
    image: "images/projects/kgf-logo.png",
    tags: ["react", "javascript", "css", "videoEditing"],
    liveview: "https://kgffarmingindia.com/",
    alt: "Kamauput Growth Farming — KGF | Agriculture & Eco Farming",
  },
  {
    id: 5,
    name: "GrowWell",
    description: "Growth-focused digital platform with marketing tools, analytics, and business management features to help businesses scale.",
    image: "images/projects/gw-logo.png",
    tags: ["react", "mongodb", "express", "javascript"],
    liveview: "https://growwell.com",
    alt: "GrowWell Business Platform",
  },
  {
    id: 6,
    name: "Dr. KPS Clinic",
    description: "Multispeciality hospital website with doctor profiles, appointment booking, 24/7 emergency info, and patient services for Kharar, Chandigarh.",
    image: "images/projects/kps-logo.png",
    tags: ["react", "javascript", "videoEditing", "css"],
    liveview: "https://drkpsclinic.com",
    alt: "Dr. KPS Clinic - Multispeciality Hospital",
  },
  {
    id: 7,
    name: "Mehta Hospital",
    description:
      "Premium healthcare website for Kharar, Punjab — services, doctors, 24/7 emergency info, and a polished patient-facing experience aligned with the hospital brand.",
    image: "images/projects/mehta-logo.png",
    tags: ["react", "javascript", "css", "videoEditing"],
    liveview: "https://mehtahospitalkharar.com/",
    alt: "Mehta Hospital | Premium Healthcare in Kharar, Punjab",
  },
  {
    id: 8,
    name: "Mindsurve",
    description:
      "Modern survey and research platform with data collection, analytics, and insights dashboard for market research.",
    image: "images/projects/ms-logo.png",
    tags: ["react", "javascript", "mongodb", "express"],
    liveview: "https://mindsurve.com",
    alt: "Mindsurve Research Platform",
  },
  {
    id: 9,
    name: "Tikun CRM",
    description:
      "Business CRM platform for leads, clients, and sales pipeline management — built for teams to track deals and grow revenue.",
    image: "images/projects/tikun-logo.svg",
    tags: ["react", "javascript", "mongodb", "express"],
    liveview: "https://tikuncrm.com",
    alt: "Tikun CRM — Customer Relationship Management",
  },
  {
    id: 10,
    name: "Ziva Hospital",
    description:
      "Multispeciality hospital website for Ziva in Mundi Kharar — 24/7 emergency care, doctor profiles, specialties, and appointment booking at zivahospital.in.",
    image: "images/projects/ziva-logo.png",
    tags: ["react", "javascript", "css", "videoEditing"],
    liveview: "https://zivahospital.in/",
    alt: "Ziva Multispeciality Hospital | 24/7 Care in Kharar, Punjab",
  },
];
